server:
  "[port]": 80

spring:
  profiles:
    active: dev
  devtools:
    livereload:
      "[enabled]": true
  datasource:
    "[driver-class-name]": com.mysql.cj.jdbc.Driver
    "[url]": jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    "[username]": root
    "[password]":
    hikari:
      "[maximum-pool-size]": 20
      "[connection-timeout]": 20000

  jpa:
    "[generate-ddl]": true
    hibernate:
      "[ddl-auto]": update
      "[show_sql]": true
    "[open-in-view]": false
    "[show-sql]": true
    properties:
      hibernate:
        "[format_sql]": true
    "[database-platform]": org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    "[cache]": false