server:
  port: 80

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
